//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carInfoTable
    {
        public int idCar { get; set; }
        public string brandCar { get; set; }
        public string modelCar { get; set; }
        public string yearCar { get; set; }
        public string numberSeats { get; set; }
        public Nullable<double> priceCar { get; set; }
    }
}
