//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RentCarEntities1 : DbContext
    {
        public RentCarEntities1()
            : base("name=RentCarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<userTable> userTable { get; set; }
        public virtual DbSet<carInfoTable> carInfoTable { get; set; }
        public virtual DbSet<RentCarTable> RentCarTable { get; set; }
    
        public virtual ObjectResult<SpGetModelCarByBrand_Result> SpGetModelCarByBrand(string brand)
        {
            var brandParameter = brand != null ?
                new ObjectParameter("brand", brand) :
                new ObjectParameter("brand", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpGetModelCarByBrand_Result>("SpGetModelCarByBrand", brandParameter);
        }
    }
}
